platform :ios, '9.0'

install! 'cocoapods',
           :deterministic_uuids => false


target 'ios' do
  use_frameworks!
  pod 'testj2objclib', :path => '../moshi'
end

target 'iosTests' do
  use_frameworks!
  pod 'testj2objclib', :path => '../moshi'
end